id: P009292
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W453
  title: བཤེས་སྤྲིངས་རྣམ་བཤད
  author: ''
  volumes:
    480d4ccddb534c14b90992748989e63e:
      image_group_id: I3582
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
